test2/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ImportController@index');
Route::post('/import', 'ImportController@import')->name('import');
Route::get('/statistic', 'StatisticController@index')->name('statistic');
Route::get('/users-list', 'UsersController@index')->name('users-list');

test2/app/Country.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    public $timestamps = false;

    protected $fillable = ['name'];

    public function usersCount()
    {
        return $this->hasMany('App\User', 'country_id', 'id');
    }
}

test2/app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    public $timestamps = false;

    protected $fillable = ['firstname', 'lastname', 'gender', 'country_id', 'age', 'created'];

    public function country()
    {
        return $this->hasOne('App\Country', 'id', 'country_id');
    }
}

test2/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

test2/app/Http/Controllers/ImportController.php
<?php

namespace App\Http\Controllers;

use App\Country;
use App\CustomClasses\ChunkReadFilter;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use PhpOffice\PhpSpreadsheet\Reader\Xlsx;


class ImportController extends Controller
{
    private $usersData = [];

    public function index()
    {
        return view('import.index');
    }

    public function import(Request $request)
    {
        $mem_start = memory_get_usage();
        set_time_limit(1800);

        $mimes = ['xlsx', 'xls', 'docx', 'ppt', 'odt', 'ods', 'odp'];
        if (!$request->file('file')) {
            return back()->with('error', 'You need to upload file');
        } elseif(!in_array(strtolower($request->file('file')->getClientOriginalExtension()), $mimes)) {
            return back()->with('error', 'Wrong file type');
        }

        $filePath = $request->file('file')->getRealPath();
        $chunkSize = 2000;
        $startRow = 2;
        $stop = false;
        $countColumns = 6;

        $objReader = new Xlsx();
        $objReader->setReadDataOnly(true);

        $chunkFilter = new ChunkReadFilter();
        $objReader->setReadFilter($chunkFilter);
        while (!$stop ) {
            $chunkFilter->setRows($startRow, $chunkSize);
            $objPHPExcel = $objReader->load($filePath);
            $objPHPExcel->setActiveSheetIndex(0);
            $objWorksheet = $objPHPExcel->getActiveSheet();

            for ($i = $startRow; $i < $startRow + $chunkSize; $i++) {
                if ($stop) continue;
                for ($col = 1; $col <= $countColumns; ++$col) {
                    $value = $objWorksheet->getCellByColumnAndRow($col, $i)->getValue();
                    if (!$value) {
                        $stop = true;
                        continue;
                    }
                    $this->usersData[$i][] = $value;
                }
            }

            $objPHPExcel->disconnectWorksheets();
            unset($objPHPExcel);
            $startRow += $chunkSize;
        }

        if ($this->usersData) {
            foreach ($this->usersData as $user) {
                $gender = strtolower($user[2]) == 'male' ? 1 : 0;
                $country = Country::firstOrCreate(['name' => $user[3]]);
                $created = \DateTime::createFromFormat("d/m/Y", $user[5]);
                User::create([
                    'firstname' => $user[0],
                    'lastname' => $user[1],
                    'gender' => $gender,
                    'country_id' => $country->id,
                    'age' => $user[4],
                    'created' => $created,
                ]);
            }
        }

        return back()->with('success', 'Excel Data Imported successfully. Memory used: '. (memory_get_usage() - $mem_start));
    }
}

test2/app/Http/Controllers/StatisticController.php
<?php

namespace App\Http\Controllers;

use App\Country;
use App\CustomClasses\ChunkReadFilter;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use PhpOffice\PhpSpreadsheet\Reader\Xlsx;


class StatisticController extends Controller
{

    public function index()
    {
        $statistic = [
            'count_users'   => User::all()->count(),
            'count_m'       => User::where('gender', 1)->count(),
            'count_f'       => User::where('gender', 0)->count(),
            'average_age'   => User::all()->avg('age'),
            'average_age_m' => User::where('gender', 1)->avg('age'),
            'average_age_f' => User::where('gender', 0)->avg('age'),
            'countries'     => Country::withCount('usersCount')->get()
        ];

        return view('statistic.index', compact("statistic"));
    }
}

test2/app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Country;
use App\CustomClasses\ChunkReadFilter;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use PhpOffice\PhpSpreadsheet\Reader\Xlsx;


class UsersController extends Controller
{

    public function index()
    {
        $users = User::with("country")->paginate(15);

        return view('users.index', compact('users'));
    }
}

test2/resources/views/import/form.blade.php
<form action="{{ route('import') }}" method="post" enctype="multipart/form-data">
    @csrf
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group row">
                    <label for="file">
                        <h3>Upload your file</h3>
                        <p class="file-block">
                            <span class="inputFile">Add Your File</span>
                            <button class="cross" type="button">&times;</button>
                        </p>
                    </label>
                    <input class="hide" id="file" type="file" name="file"/>
                </div>
                <button class="btn btn-primary" type="submit">Upload</button>
            </div>
        </div>
    </div>
</form>

test2/resources/views/import/index.blade.php
@extends('layouts.app')

@section('header')
    @include('layouts.components.header')
@endsection

@section('content')
    <div class="container">
        @include('import.form')

    </div>
@endsection

test2/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Sripts -->

    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

</head>
<body>
    @yield('header')

    @yield('content')

    @yield('footer')
</body>
</html>

test2/resources/views/layouts/components/header.blade.php
<header class="header">
    <hr>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1>Test 2</h1>
            </div>
            <div class="col-md-4">
                <a class="btn btn-primary" href="{{ route('statistic') }}">{{ __('Statistic') }}</a>
                <a class="btn btn-primary" href="{{ route('users-list') }}">{{ __('Users') }}</a>
            </div>
        </div>
    </div>
    <hr>
    <div class="container">
        @if (Session::has('success'))
            <div class="alert alert-info">
                <span>{{ Session::get('success') }}</span>
            </div>
        @endif

        @if (Session::has('error'))
            <div class="alert alert-danger">
                {{ Session::get('error') }}
            </div>
        @endif
    </div>
</header>

test2/resources/views/statistic/index.blade.php
@extends('layouts.app')

@section('header')
    @include('layouts.components.header')
@endsection

@section('content')
    <div class="container page-title">
        <div class="row">
            <div class="col-md-8">
                <h2>Statistics by users</h2>
            </div>
            <div class="col-md-2">
                <a href="{{ url('/') }}" class="btn btn-primary">Back to Homepage</a>
            </div>
        </div>
    </div>

    <div class="container users-list-table">
        @if ($statistic)
            <div class="row">
                <div class="col-md-10">
                    <h3>Количество пользователей</h3>
                </div>
                <div class="col-md-2">
                    <h3>{{ $statistic['count_users'] }}</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-10">
                    <h3>Количество женщин</h3>
                </div>
                <div class="col-md-2">
                    <h3>{{ $statistic['count_f'] }}</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-10">
                    <h3>Количество мужчин</h3>
                </div>
                <div class="col-md-2">
                    <h3>{{ $statistic['count_m'] }}</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-10">
                    <h3>Средний возраст всех сотрудников</h3>
                </div>
                <div class="col-md-2">
                    <h3>{{ number_format($statistic['average_age'], 2) }}</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-10">
                    <h3>Средний возраст мужчин</h3>
                </div>
                <div class="col-md-2">
                    <h3>{{ number_format($statistic['average_age_m'], 2) }}</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-10">
                    <h3>Средний возраст женщин</h3>
                </div>
                <div class="col-md-2">
                    <h3>{{ number_format($statistic['average_age_f'], 2) }}</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h3>Количество пользователей из каждой страны:</h3>
                </div>
            </div>
            @if($statistic['countries'])
                @foreach($statistic['countries'] as $country)
                    <div class="row">
                        <div class="col-md-9 offset-md-1">
                            <h3>- {{ $country->name }}</h3>
                        </div>
                        <div class="col-md-2">
                            <h3>{{ $country->users_count_count }}</h3>
                        </div>
                    </div>

                @endforeach
            @endif
        @else
            <h2>There is no users in database</h2>
        @endif
    </div>
@endsection

test2/resources/views/users/index.blade.php
@extends('layouts.app')

@section('header')
    @include('layouts.components.header')
@endsection

@section('content')
    <div class="container page-title">
        <div class="row">
            <div class="col-md-8">
                <h2>Users list</h2>
            </div>
            <div class="col-md-2">
                <a href="{{ url('/') }}" class="btn btn-primary">Back to Homepage</a>
            </div>
        </div>
    </div>

    <div class="container users-list-table">
        @if (count($users))
            @foreach ($users as $user)
                @if ($loop->first)
                    <div class="row user-list-header">
                        <div class="col-md-1 my-auto">ID</div>
                        <div class="col-md-2 my-auto">First name</div>
                        <div class="col-md-2 my-auto">Last name</div>
                        <div class="col-md-2 my-auto">Gender</div>
                        <div class="col-md-2 my-auto">Country</div>
                        <div class="col-md-1 my-auto">Age</div>
                        <div class="col-md-2 my-auto">Created</div>
                    </div>
                @endif
                    <div class="row user-list">
                        <div class="col-md-1 my-auto">{{ $user->id }}</div>
                        <div class="col-md-2 my-auto">{{ $user->firstname }}</div>
                        <div class="col-md-2 my-auto">{{ $user->lastname }}</div>
                        <div class="col-md-2 my-auto">{{ $user->gender ? "Male" : "Famale" }}</div>
                        <div class="col-md-2 my-auto">{{ $user->country->name }}</div>
                        <div class="col-md-1 my-auto">{{ $user->age }}</div>
                        <div class="col-md-2 my-auto">{{ $user->created }}</div>
                    </div>
            @endforeach
        @else
            <h2>There is no users in database</h2>
        @endif
    </div>

    @if (count($users))
        <div class="container users-list-footer">
            {{ $users->links() }}
        </div>
    @endif
@endsection